/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Wed Jul 29 16:41:49 2026.
 */

#ifndef BOOTER_H
#define BOOTER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BOOTER_BOOT_TX_FRAME_ID (0x202u)
#define BOOTER_BOOT_RX_FRAME_ID (0x201u)
#define BOOTER_BOOT_DATA_FRAME_ID (0x200u)

/* Frame lengths in bytes. */
#define BOOTER_BOOT_TX_LENGTH (8u)
#define BOOTER_BOOT_RX_LENGTH (8u)
#define BOOTER_BOOT_DATA_LENGTH (8u)

/* Extended or standard frame types. */
#define BOOTER_BOOT_TX_IS_EXTENDED (0)
#define BOOTER_BOOT_RX_IS_EXTENDED (0)
#define BOOTER_BOOT_DATA_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define BOOTER_BOOT_TX_BOOT_CMD_BOOT_INIT_CHOICE (0u)
#define BOOTER_BOOT_TX_BOOT_CMD_TRANSMIT_START_CHOICE (1u)
#define BOOTER_BOOT_TX_BOOT_CMD_TRANSMIT_END_CHOICE (2u)
#define BOOTER_BOOT_TX_BOOT_CMD_DEPRECATED_CHOICE (3u)

#define BOOTER_BOOT_TX_NODE_ID_PEDAL_CHOICE (0u)
#define BOOTER_BOOT_TX_NODE_ID_REFRI_CHOICE (1u)
#define BOOTER_BOOT_TX_NODE_ID_LVBMS_CHOICE (2u)
#define BOOTER_BOOT_TX_NODE_ID_ECU_CHOICE (3u)
#define BOOTER_BOOT_TX_NODE_ID_STEER_CHOICE (4u)

#define BOOTER_BOOT_TX_HEX_CRC__CHOICE (0u)

#define BOOTER_BOOT_TX_HEX_SIZE__CHOICE (0u)

#define BOOTER_BOOT_RX_BOOT_CMD_ACK_CHOICE (0u)
#define BOOTER_BOOT_RX_BOOT_CMD_NACK_CHOICE (1u)
#define BOOTER_BOOT_RX_BOOT_CMD_PERCENT_CHOICE (2u)

/* Frame Names. */
#define BOOTER_BOOT_TX_NAME "BOOT_TX"
#define BOOTER_BOOT_RX_NAME "BOOT_RX"
#define BOOTER_BOOT_DATA_NAME "BOOT_DATA"

/* Signal Names. */
#define BOOTER_BOOT_TX_BOOT_CMD_NAME "BOOT_CMD"
#define BOOTER_BOOT_TX_NODE_ID_NAME "NODE_ID"
#define BOOTER_BOOT_TX_HEX_CRC_NAME "HEX_CRC"
#define BOOTER_BOOT_TX_HEX_SIZE_NAME "HEX_SIZE"
#define BOOTER_BOOT_RX_BOOT_CMD_NAME "BOOT_CMD"
#define BOOTER_BOOT_RX_PERCENT_NAME "PERCENT"
#define BOOTER_BOOT_RX_ACK_NAME "ACK"
#define BOOTER_BOOT_RX_NACK_NAME "NACK"
#define BOOTER_BOOT_DATA_DATA_NAME "DATA"
#define BOOTER_BOOT_DATA_ADRESS_NAME "ADRESS"

/**
 * Signals in message BOOT_TX.
 *
 * All signal values are as on the CAN bus.
 */
struct booter_boot_tx_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t boot_cmd;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t node_id;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t hex_crc;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t hex_size;
};

/**
 * Signals in message BOOT_RX.
 *
 * All signal values are as on the CAN bus.
 */
struct booter_boot_rx_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t boot_cmd;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t percent;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ack;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nack;
};

/**
 * Signals in message BOOT_DATA.
 *
 * All signal values are as on the CAN bus.
 */
struct booter_boot_data_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t data;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t adress;
};

/**
 * Pack message BOOT_TX.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int booter_boot_tx_pack(
    uint8_t *dst_p,
    const struct booter_boot_tx_t *src_p,
    size_t size);

/**
 * Unpack message BOOT_TX.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int booter_boot_tx_unpack(
    struct booter_boot_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BOOT_TX.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int booter_boot_tx_init(struct booter_boot_tx_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t booter_boot_tx_boot_cmd_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_tx_boot_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_tx_boot_cmd_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t booter_boot_tx_node_id_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_tx_node_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_tx_node_id_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t booter_boot_tx_hex_crc_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_tx_hex_crc_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_tx_hex_crc_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t booter_boot_tx_hex_size_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_tx_hex_size_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_tx_hex_size_is_in_range(uint32_t value);

/**
 * Pack message BOOT_RX.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int booter_boot_rx_pack(
    uint8_t *dst_p,
    const struct booter_boot_rx_t *src_p,
    size_t size);

/**
 * Unpack message BOOT_RX.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int booter_boot_rx_unpack(
    struct booter_boot_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BOOT_RX.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int booter_boot_rx_init(struct booter_boot_rx_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t booter_boot_rx_boot_cmd_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_rx_boot_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_rx_boot_cmd_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t booter_boot_rx_percent_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_rx_percent_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_rx_percent_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t booter_boot_rx_ack_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_rx_ack_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_rx_ack_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t booter_boot_rx_nack_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_rx_nack_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_rx_nack_is_in_range(uint8_t value);

/**
 * Pack message BOOT_DATA.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int booter_boot_data_pack(
    uint8_t *dst_p,
    const struct booter_boot_data_t *src_p,
    size_t size);

/**
 * Unpack message BOOT_DATA.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int booter_boot_data_unpack(
    struct booter_boot_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BOOT_DATA.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int booter_boot_data_init(struct booter_boot_data_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t booter_boot_data_data_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_data_data_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_data_data_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t booter_boot_data_adress_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float booter_boot_data_adress_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool booter_boot_data_adress_is_in_range(uint32_t value);


#ifdef __cplusplus
}
#endif

#endif
