/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Wed Jul 29 16:41:49 2026.
 */

#include <string.h>

#include "booter.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int booter_boot_tx_pack(
    uint8_t *dst_p,
    const struct booter_boot_tx_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->boot_cmd, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->node_id, 4u, 0xf0u);

    switch (src_p->boot_cmd) {

    case 0:
        break;

    case 1:
        dst_p[1] |= pack_left_shift_u32(src_p->hex_crc, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u32(src_p->hex_crc, 8u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(src_p->hex_crc, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(src_p->hex_crc, 24u, 0xffu);
        dst_p[5] |= pack_left_shift_u32(src_p->hex_size, 0u, 0xffu);
        dst_p[6] |= pack_right_shift_u32(src_p->hex_size, 8u, 0xffu);
        dst_p[7] |= pack_right_shift_u32(src_p->hex_size, 16u, 0xffu);
        break;

    case 2:
        break;

    case 3:
        break;

    default:
        break;
    }

    return (8);
}

int booter_boot_tx_unpack(
    struct booter_boot_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->boot_cmd = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->node_id = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);

    switch (dst_p->boot_cmd) {

    case 0:
        break;

    case 1:
        dst_p->hex_crc = unpack_right_shift_u32(src_p[1], 0u, 0xffu);
        dst_p->hex_crc |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
        dst_p->hex_crc |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        dst_p->hex_crc |= unpack_left_shift_u32(src_p[4], 24u, 0xffu);
        dst_p->hex_size = unpack_right_shift_u32(src_p[5], 0u, 0xffu);
        dst_p->hex_size |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
        dst_p->hex_size |= unpack_left_shift_u32(src_p[7], 16u, 0xffu);
        break;

    case 2:
        break;

    case 3:
        break;

    default:
        break;
    }

    return (0);
}

int booter_boot_tx_init(struct booter_boot_tx_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct booter_boot_tx_t));

    return 0;
}

uint8_t booter_boot_tx_boot_cmd_encode(float value)
{
    return (uint8_t)(value);
}

float booter_boot_tx_boot_cmd_decode(uint8_t value)
{
    return ((float)value);
}

bool booter_boot_tx_boot_cmd_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t booter_boot_tx_node_id_encode(float value)
{
    return (uint8_t)(value);
}

float booter_boot_tx_node_id_decode(uint8_t value)
{
    return ((float)value);
}

bool booter_boot_tx_node_id_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint32_t booter_boot_tx_hex_crc_encode(float value)
{
    return (uint32_t)(value);
}

float booter_boot_tx_hex_crc_decode(uint32_t value)
{
    return ((float)value);
}

bool booter_boot_tx_hex_crc_is_in_range(uint32_t value)
{
    return (value <= 3u);
}

uint32_t booter_boot_tx_hex_size_encode(float value)
{
    return (uint32_t)(value);
}

float booter_boot_tx_hex_size_decode(uint32_t value)
{
    return ((float)value);
}

bool booter_boot_tx_hex_size_is_in_range(uint32_t value)
{
    return (value <= 3u);
}

int booter_boot_rx_pack(
    uint8_t *dst_p,
    const struct booter_boot_rx_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->boot_cmd, 0u, 0x0fu);

    switch (src_p->boot_cmd) {

    case 0:
        dst_p[0] |= pack_left_shift_u8(src_p->ack, 4u, 0x10u);
        break;

    case 1:
        dst_p[0] |= pack_left_shift_u8(src_p->nack, 4u, 0x10u);
        break;

    case 2:
        dst_p[0] |= pack_left_shift_u8(src_p->percent, 4u, 0xf0u);
        dst_p[1] |= pack_right_shift_u8(src_p->percent, 4u, 0x0fu);
        break;

    default:
        break;
    }

    return (8);
}

int booter_boot_rx_unpack(
    struct booter_boot_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->boot_cmd = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    switch (dst_p->boot_cmd) {

    case 0:
        dst_p->ack = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
        break;

    case 1:
        dst_p->nack = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
        break;

    case 2:
        dst_p->percent = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
        dst_p->percent |= unpack_left_shift_u8(src_p[1], 4u, 0x0fu);
        break;

    default:
        break;
    }

    return (0);
}

int booter_boot_rx_init(struct booter_boot_rx_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct booter_boot_rx_t));

    return 0;
}

uint8_t booter_boot_rx_boot_cmd_encode(float value)
{
    return (uint8_t)(value);
}

float booter_boot_rx_boot_cmd_decode(uint8_t value)
{
    return ((float)value);
}

bool booter_boot_rx_boot_cmd_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t booter_boot_rx_percent_encode(float value)
{
    return (uint8_t)(value);
}

float booter_boot_rx_percent_decode(uint8_t value)
{
    return ((float)value);
}

bool booter_boot_rx_percent_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t booter_boot_rx_ack_encode(float value)
{
    return (uint8_t)(value);
}

float booter_boot_rx_ack_decode(uint8_t value)
{
    return ((float)value);
}

bool booter_boot_rx_ack_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t booter_boot_rx_nack_encode(float value)
{
    return (uint8_t)(value);
}

float booter_boot_rx_nack_decode(uint8_t value)
{
    return ((float)value);
}

bool booter_boot_rx_nack_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int booter_boot_data_pack(
    uint8_t *dst_p,
    const struct booter_boot_data_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->data, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->data, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->data, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->data, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->adress, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->adress, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->adress, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->adress, 24u, 0xffu);

    return (8);
}

int booter_boot_data_unpack(
    struct booter_boot_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->data = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->data |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->data |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->data |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->adress = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->adress |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->adress |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->adress |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int booter_boot_data_init(struct booter_boot_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct booter_boot_data_t));

    return 0;
}

uint32_t booter_boot_data_data_encode(float value)
{
    return (uint32_t)(value);
}

float booter_boot_data_data_decode(uint32_t value)
{
    return ((float)value);
}

bool booter_boot_data_data_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint32_t booter_boot_data_adress_encode(float value)
{
    return (uint32_t)(value);
}

float booter_boot_data_adress_decode(uint32_t value)
{
    return ((float)value);
}

bool booter_boot_data_adress_is_in_range(uint32_t value)
{
    return (value <= 1u);
}
