/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Wed Jul 29 16:41:49 2026.
 */

#include <string.h>

#include "charger.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int charger_read_object_pack(
    uint8_t *dst_p,
    const struct charger_read_object_t *src_p,
    size_t size)
{
    uint32_t read_ms_total_current;
    uint32_t read_ms_total_power;
    uint32_t read_ms_total_voltage;
    uint32_t read_nominal_current;
    uint32_t read_nominal_power;
    uint32_t read_nominal_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->read_mux, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->read_mux, 0u, 0xffu);

    switch (src_p->read_mux) {

    case 0:
        break;

    case 1:
        break;

    case 21:
        break;

    case 41:
        break;

    case 61:
        break;

    case 81:
        break;

    case 101:
        break;

    case 121:
        memcpy(&read_nominal_voltage, &src_p->read_nominal_voltage, sizeof(read_nominal_voltage));
        dst_p[2] |= pack_right_shift_u32(read_nominal_voltage, 24u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(read_nominal_voltage, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(read_nominal_voltage, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u32(read_nominal_voltage, 0u, 0xffu);
        break;

    case 123:
        memcpy(&read_nominal_current, &src_p->read_nominal_current, sizeof(read_nominal_current));
        dst_p[2] |= pack_right_shift_u32(read_nominal_current, 24u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(read_nominal_current, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(read_nominal_current, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u32(read_nominal_current, 0u, 0xffu);
        break;

    case 125:
        memcpy(&read_nominal_power, &src_p->read_nominal_power, sizeof(read_nominal_power));
        dst_p[2] |= pack_right_shift_u32(read_nominal_power, 24u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(read_nominal_power, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(read_nominal_power, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u32(read_nominal_power, 0u, 0xffu);
        break;

    case 131:
        break;

    case 151:
        break;

    case 171:
        break;

    case 191:
        break;

    case 211:
        break;

    case 231:
        break;

    case 402:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_remote, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_remote, 0u, 0xffu);
        break;

    case 405:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_dc_output, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_dc_output, 0u, 0xffu);
        break;

    case 407:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_dc_after_pf_alarm, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_dc_after_pf_alarm, 0u, 0xffu);
        break;

    case 408:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_dc_after_power_on, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_dc_after_power_on, 0u, 0xffu);
        break;

    case 416:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_ai_vref, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_ai_vref, 0u, 0xffu);
        break;

    case 417:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_ai_rem_sb_level, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_ai_rem_sb_level, 0u, 0xffu);
        break;

    case 418:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_ai_rem_sb_action, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_ai_rem_sb_action, 0u, 0xffu);
        break;

    case 425:
        dst_p[2] |= pack_right_shift_u16(src_p->read_coil_dc_after_remote, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_coil_dc_after_remote, 0u, 0xffu);
        break;

    case 500:
        dst_p[2] |= pack_right_shift_u16(src_p->read_voltage, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_voltage, 0u, 0xffu);
        break;

    case 501:
        dst_p[2] |= pack_right_shift_u16(src_p->read_current, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_current, 0u, 0xffu);
        break;

    case 502:
        dst_p[2] |= pack_right_shift_u16(src_p->read_power, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_power, 0u, 0xffu);
        break;

    case 505:
        dst_p[2] |= pack_left_shift_u8(src_p->read_status_alarm_rem_sb, 6u, 0x40u);
        dst_p[2] |= pack_left_shift_u8(src_p->read_status_alarm_mss, 5u, 0x20u);
        dst_p[3] |= pack_left_shift_u8(src_p->read_status_alarm_pf, 5u, 0x20u);
        dst_p[3] |= pack_left_shift_u8(src_p->read_status_alarm_ot, 3u, 0x08u);
        dst_p[3] |= pack_left_shift_u8(src_p->read_status_alarm_opp, 2u, 0x04u);
        dst_p[3] |= pack_left_shift_u8(src_p->read_status_alarm_ocp, 1u, 0x02u);
        dst_p[3] |= pack_left_shift_u8(src_p->read_status_alarm_ovp, 0u, 0x01u);
        dst_p[4] |= pack_left_shift_u8(src_p->read_status_alarms, 7u, 0x80u);
        dst_p[4] |= pack_left_shift_u8(src_p->read_status_ext_sense, 6u, 0x40u);
        dst_p[4] |= pack_left_shift_u8(src_p->read_status_remote, 3u, 0x08u);
        dst_p[4] |= pack_left_shift_u8(src_p->read_status_reg_act, 1u, 0x06u);
        dst_p[5] |= pack_left_shift_u8(src_p->read_status_dc_output, 7u, 0x80u);
        dst_p[5] |= pack_left_shift_u8(src_p->read_status_ms_type, 6u, 0x40u);
        dst_p[5] |= pack_left_shift_u8(src_p->read_status_access, 0u, 0x1fu);
        break;

    case 507:
        dst_p[2] |= pack_right_shift_u16(src_p->read_actual_voltage, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_actual_voltage, 0u, 0xffu);
        break;

    case 508:
        dst_p[2] |= pack_right_shift_u16(src_p->read_actual_current, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_actual_current, 0u, 0xffu);
        break;

    case 509:
        dst_p[2] |= pack_right_shift_u16(src_p->read_actual_power, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_actual_power, 0u, 0xffu);
        break;

    case 511:
        dst_p[5] |= pack_left_shift_u8(src_p->read_status_alarm_sf, 1u, 0x02u);
        break;

    case 520:
        dst_p[2] |= pack_right_shift_u16(src_p->read_alarm_count_ov, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_alarm_count_ov, 0u, 0xffu);
        break;

    case 521:
        dst_p[2] |= pack_right_shift_u16(src_p->read_alarm_count_oc, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_alarm_count_oc, 0u, 0xffu);
        break;

    case 522:
        dst_p[2] |= pack_right_shift_u16(src_p->read_alarm_count_op, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_alarm_count_op, 0u, 0xffu);
        break;

    case 523:
        dst_p[2] |= pack_right_shift_u16(src_p->read_alarm_count_ot, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_alarm_count_ot, 0u, 0xffu);
        break;

    case 524:
        dst_p[2] |= pack_right_shift_u16(src_p->read_alarm_count_pf, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_alarm_count_pf, 0u, 0xffu);
        break;

    case 527:
        dst_p[2] |= pack_right_shift_u16(src_p->read_alarm_count_sf, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_alarm_count_sf, 0u, 0xffu);
        break;

    case 550:
        dst_p[2] |= pack_right_shift_u16(src_p->read_protection_ovp, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_protection_ovp, 0u, 0xffu);
        break;

    case 553:
        dst_p[2] |= pack_right_shift_u16(src_p->read_protection_ocp, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_protection_ocp, 0u, 0xffu);
        break;

    case 556:
        dst_p[2] |= pack_right_shift_u16(src_p->read_protection_opp, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_protection_opp, 0u, 0xffu);
        break;

    case 650:
        dst_p[2] |= pack_right_shift_u16(src_p->read_ms_coil_link_mode, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_ms_coil_link_mode, 0u, 0xffu);
        break;

    case 653:
        dst_p[2] |= pack_right_shift_u16(src_p->read_ms_coil_enable_ms, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_ms_coil_enable_ms, 0u, 0xffu);
        break;

    case 655:
        dst_p[2] |= pack_right_shift_u16(src_p->read_ms_condition, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_ms_condition, 0u, 0xffu);
        break;

    case 656:
        memcpy(&read_ms_total_voltage, &src_p->read_ms_total_voltage, sizeof(read_ms_total_voltage));
        dst_p[2] |= pack_right_shift_u32(read_ms_total_voltage, 24u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(read_ms_total_voltage, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(read_ms_total_voltage, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u32(read_ms_total_voltage, 0u, 0xffu);
        break;

    case 658:
        memcpy(&read_ms_total_current, &src_p->read_ms_total_current, sizeof(read_ms_total_current));
        dst_p[2] |= pack_right_shift_u32(read_ms_total_current, 24u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(read_ms_total_current, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(read_ms_total_current, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u32(read_ms_total_current, 0u, 0xffu);
        break;

    case 660:
        memcpy(&read_ms_total_power, &src_p->read_ms_total_power, sizeof(read_ms_total_power));
        dst_p[2] |= pack_right_shift_u32(read_ms_total_power, 24u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(read_ms_total_power, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u32(read_ms_total_power, 8u, 0xffu);
        dst_p[5] |= pack_left_shift_u32(read_ms_total_power, 0u, 0xffu);
        break;

    case 662:
        dst_p[2] |= pack_right_shift_u16(src_p->read_ms_units, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_ms_units, 0u, 0xffu);
        break;

    case 666:
        dst_p[2] |= pack_right_shift_u16(src_p->read_ms_coil_termination, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_ms_coil_termination, 0u, 0xffu);
        break;

    case 667:
        dst_p[2] |= pack_right_shift_u16(src_p->read_ms_coil_termination_bias, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_ms_coil_termination_bias, 0u, 0xffu);
        break;

    case 9000:
        dst_p[2] |= pack_right_shift_u16(src_p->read_limit_umax, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_limit_umax, 0u, 0xffu);
        break;

    case 9001:
        dst_p[2] |= pack_right_shift_u16(src_p->read_limit_umin, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_limit_umin, 0u, 0xffu);
        break;

    case 9002:
        dst_p[2] |= pack_right_shift_u16(src_p->read_limit_imax, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_limit_imax, 0u, 0xffu);
        break;

    case 9003:
        dst_p[2] |= pack_right_shift_u16(src_p->read_limit_imin, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_limit_imin, 0u, 0xffu);
        break;

    case 9004:
        dst_p[2] |= pack_right_shift_u16(src_p->read_limit_pmax, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u16(src_p->read_limit_pmax, 0u, 0xffu);
        break;

    case 65535:
        dst_p[2] |= pack_left_shift_u8(src_p->read_last_com_errror, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int charger_read_object_unpack(
    struct charger_read_object_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t read_ms_total_current;
    uint32_t read_ms_total_power;
    uint32_t read_ms_total_voltage;
    uint32_t read_nominal_current;
    uint32_t read_nominal_power;
    uint32_t read_nominal_voltage;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->read_mux = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->read_mux |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    switch (dst_p->read_mux) {

    case 0:
        break;

    case 1:
        break;

    case 21:
        break;

    case 41:
        break;

    case 61:
        break;

    case 81:
        break;

    case 101:
        break;

    case 121:
        read_nominal_voltage = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
        read_nominal_voltage |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        read_nominal_voltage |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
        read_nominal_voltage |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
        memcpy(&dst_p->read_nominal_voltage, &read_nominal_voltage, sizeof(dst_p->read_nominal_voltage));
        break;

    case 123:
        read_nominal_current = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
        read_nominal_current |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        read_nominal_current |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
        read_nominal_current |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
        memcpy(&dst_p->read_nominal_current, &read_nominal_current, sizeof(dst_p->read_nominal_current));
        break;

    case 125:
        read_nominal_power = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
        read_nominal_power |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        read_nominal_power |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
        read_nominal_power |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
        memcpy(&dst_p->read_nominal_power, &read_nominal_power, sizeof(dst_p->read_nominal_power));
        break;

    case 131:
        break;

    case 151:
        break;

    case 171:
        break;

    case 191:
        break;

    case 211:
        break;

    case 231:
        break;

    case 402:
        dst_p->read_coil_remote = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_remote |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 405:
        dst_p->read_coil_dc_output = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_dc_output |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 407:
        dst_p->read_coil_dc_after_pf_alarm = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_dc_after_pf_alarm |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 408:
        dst_p->read_coil_dc_after_power_on = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_dc_after_power_on |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 416:
        dst_p->read_coil_ai_vref = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_ai_vref |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 417:
        dst_p->read_coil_ai_rem_sb_level = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_ai_rem_sb_level |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 418:
        dst_p->read_coil_ai_rem_sb_action = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_ai_rem_sb_action |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 425:
        dst_p->read_coil_dc_after_remote = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_coil_dc_after_remote |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 500:
        dst_p->read_voltage = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_voltage |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 501:
        dst_p->read_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 502:
        dst_p->read_power = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_power |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 505:
        dst_p->read_status_alarm_rem_sb = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
        dst_p->read_status_alarm_mss = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
        dst_p->read_status_alarm_pf = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
        dst_p->read_status_alarm_ot = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
        dst_p->read_status_alarm_opp = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
        dst_p->read_status_alarm_ocp = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
        dst_p->read_status_alarm_ovp = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
        dst_p->read_status_alarms = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
        dst_p->read_status_ext_sense = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
        dst_p->read_status_remote = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
        dst_p->read_status_reg_act = unpack_right_shift_u8(src_p[4], 1u, 0x06u);
        dst_p->read_status_dc_output = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
        dst_p->read_status_ms_type = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
        dst_p->read_status_access = unpack_right_shift_u8(src_p[5], 0u, 0x1fu);
        break;

    case 507:
        dst_p->read_actual_voltage = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_actual_voltage |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 508:
        dst_p->read_actual_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_actual_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 509:
        dst_p->read_actual_power = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_actual_power |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 511:
        dst_p->read_status_alarm_sf = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
        break;

    case 520:
        dst_p->read_alarm_count_ov = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_alarm_count_ov |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 521:
        dst_p->read_alarm_count_oc = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_alarm_count_oc |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 522:
        dst_p->read_alarm_count_op = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_alarm_count_op |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 523:
        dst_p->read_alarm_count_ot = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_alarm_count_ot |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 524:
        dst_p->read_alarm_count_pf = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_alarm_count_pf |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 527:
        dst_p->read_alarm_count_sf = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_alarm_count_sf |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 550:
        dst_p->read_protection_ovp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_protection_ovp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 553:
        dst_p->read_protection_ocp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_protection_ocp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 556:
        dst_p->read_protection_opp = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_protection_opp |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 650:
        dst_p->read_ms_coil_link_mode = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_ms_coil_link_mode |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 653:
        dst_p->read_ms_coil_enable_ms = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_ms_coil_enable_ms |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 655:
        dst_p->read_ms_condition = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_ms_condition |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 656:
        read_ms_total_voltage = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
        read_ms_total_voltage |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        read_ms_total_voltage |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
        read_ms_total_voltage |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
        memcpy(&dst_p->read_ms_total_voltage, &read_ms_total_voltage, sizeof(dst_p->read_ms_total_voltage));
        break;

    case 658:
        read_ms_total_current = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
        read_ms_total_current |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        read_ms_total_current |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
        read_ms_total_current |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
        memcpy(&dst_p->read_ms_total_current, &read_ms_total_current, sizeof(dst_p->read_ms_total_current));
        break;

    case 660:
        read_ms_total_power = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
        read_ms_total_power |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
        read_ms_total_power |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
        read_ms_total_power |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
        memcpy(&dst_p->read_ms_total_power, &read_ms_total_power, sizeof(dst_p->read_ms_total_power));
        break;

    case 662:
        dst_p->read_ms_units = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_ms_units |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 666:
        dst_p->read_ms_coil_termination = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_ms_coil_termination |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 667:
        dst_p->read_ms_coil_termination_bias = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_ms_coil_termination_bias |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 9000:
        dst_p->read_limit_umax = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_limit_umax |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 9001:
        dst_p->read_limit_umin = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_limit_umin |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 9002:
        dst_p->read_limit_imax = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_limit_imax |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 9003:
        dst_p->read_limit_imin = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_limit_imin |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 9004:
        dst_p->read_limit_pmax = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
        dst_p->read_limit_pmax |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
        break;

    case 65535:
        dst_p->read_last_com_errror = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

int charger_read_object_init(struct charger_read_object_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_read_object_t));

    return 0;
}

uint16_t charger_read_object_read_mux_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_mux_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_mux_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_ms_coil_termination_bias_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_ms_coil_termination_bias_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_coil_termination_bias_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_ms_coil_termination_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_ms_coil_termination_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_coil_termination_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_alarm_count_sf_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_alarm_count_sf_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_alarm_count_sf_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_dc_after_remote_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_dc_after_remote_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_dc_after_remote_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_actual_current_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_read_object_read_actual_current_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_read_object_read_actual_current_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_read_object_read_actual_power_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_read_object_read_actual_power_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_read_object_read_actual_power_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_read_object_read_actual_voltage_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_read_object_read_actual_voltage_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_read_object_read_actual_voltage_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

float charger_read_object_read_ms_total_voltage_encode(float value)
{
    return (float)(value);
}

float charger_read_object_read_ms_total_voltage_decode(float value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_total_voltage_is_in_range(float value)
{
    (void)value;

    return (true);
}

float charger_read_object_read_ms_total_power_encode(float value)
{
    return (float)(value);
}

float charger_read_object_read_ms_total_power_decode(float value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_total_power_is_in_range(float value)
{
    (void)value;

    return (true);
}

float charger_read_object_read_ms_total_current_encode(float value)
{
    return (float)(value);
}

float charger_read_object_read_ms_total_current_decode(float value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_total_current_is_in_range(float value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_ms_units_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_ms_units_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_units_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_ms_condition_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_ms_condition_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_condition_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_ms_coil_link_mode_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_ms_coil_link_mode_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_coil_link_mode_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_ms_coil_enable_ms_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_ms_coil_enable_ms_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_ms_coil_enable_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_alarm_count_pf_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_alarm_count_pf_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_alarm_count_pf_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_alarm_count_ot_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_alarm_count_ot_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_alarm_count_ot_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_alarm_count_op_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_alarm_count_op_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_alarm_count_op_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_alarm_count_oc_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_alarm_count_oc_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_alarm_count_oc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_alarm_count_ov_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_alarm_count_ov_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_alarm_count_ov_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t charger_read_object_read_last_com_errror_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_last_com_errror_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_last_com_errror_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_remote_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_remote_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_remote_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_dc_after_power_on_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_dc_after_power_on_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_dc_after_power_on_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_dc_output_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_dc_output_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_dc_output_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_dc_after_pf_alarm_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_dc_after_pf_alarm_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_dc_after_pf_alarm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_ai_vref_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_ai_vref_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_ai_vref_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_ai_rem_sb_level_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_ai_rem_sb_level_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_ai_rem_sb_level_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_coil_ai_rem_sb_action_encode(float value)
{
    return (uint16_t)(value);
}

float charger_read_object_read_coil_ai_rem_sb_action_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_read_object_read_coil_ai_rem_sb_action_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_read_object_read_protection_ovp_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_read_object_read_protection_ovp_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_read_object_read_protection_ovp_is_in_range(uint16_t value)
{
    return (value <= 57671u);
}

uint16_t charger_read_object_read_protection_opp_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_read_object_read_protection_opp_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_read_object_read_protection_opp_is_in_range(uint16_t value)
{
    return (value <= 57671u);
}

uint16_t charger_read_object_read_protection_ocp_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_read_object_read_protection_ocp_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_read_object_read_protection_ocp_is_in_range(uint16_t value)
{
    return (value <= 57671u);
}

uint16_t charger_read_object_read_limit_umin_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_read_object_read_limit_umin_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_read_object_read_limit_umin_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_read_object_read_limit_umax_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_read_object_read_limit_umax_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_read_object_read_limit_umax_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_read_object_read_limit_pmax_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_read_object_read_limit_pmax_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_read_object_read_limit_pmax_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_read_object_read_limit_imin_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_read_object_read_limit_imin_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_read_object_read_limit_imin_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_read_object_read_limit_imax_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_read_object_read_limit_imax_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_read_object_read_limit_imax_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_read_object_read_voltage_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_read_object_read_voltage_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_read_object_read_voltage_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_read_object_read_power_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_read_object_read_power_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_read_object_read_power_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_read_object_read_current_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_read_object_read_current_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_read_object_read_current_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

float charger_read_object_read_nominal_voltage_encode(float value)
{
    return (float)(value);
}

float charger_read_object_read_nominal_voltage_decode(float value)
{
    return ((float)value);
}

bool charger_read_object_read_nominal_voltage_is_in_range(float value)
{
    (void)value;

    return (true);
}

float charger_read_object_read_nominal_power_encode(float value)
{
    return (float)(value);
}

float charger_read_object_read_nominal_power_decode(float value)
{
    return ((float)value);
}

bool charger_read_object_read_nominal_power_is_in_range(float value)
{
    (void)value;

    return (true);
}

float charger_read_object_read_nominal_current_encode(float value)
{
    return (float)(value);
}

float charger_read_object_read_nominal_current_decode(float value)
{
    return ((float)value);
}

bool charger_read_object_read_nominal_current_is_in_range(float value)
{
    (void)value;

    return (true);
}

uint8_t charger_read_object_read_status_alarm_rem_sb_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_rem_sb_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_rem_sb_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_alarm_mss_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_mss_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_mss_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_alarm_pf_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_pf_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_pf_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_alarm_ot_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_ot_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_ot_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_alarm_opp_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_opp_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_opp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_alarm_ocp_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_ocp_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_ocp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_alarm_ovp_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_ovp_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_ovp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_alarms_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarms_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarms_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_ext_sense_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_ext_sense_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_ext_sense_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_remote_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_remote_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_remote_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_reg_act_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_reg_act_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_reg_act_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t charger_read_object_read_status_dc_output_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_dc_output_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_dc_output_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_ms_type_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_ms_type_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_ms_type_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_read_object_read_status_access_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_access_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_access_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t charger_read_object_read_status_alarm_sf_encode(float value)
{
    return (uint8_t)(value);
}

float charger_read_object_read_status_alarm_sf_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_read_object_read_status_alarm_sf_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int charger_query_object_pack(
    uint8_t *dst_p,
    const struct charger_query_object_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_right_shift_u16(src_p->query_mux, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->query_mux, 0u, 0xffu);

    return (2);
}

int charger_query_object_unpack(
    struct charger_query_object_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->query_mux = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->query_mux |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int charger_query_object_init(struct charger_query_object_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_query_object_t));

    return 0;
}

uint16_t charger_query_object_query_mux_encode(float value)
{
    return (uint16_t)(value);
}

float charger_query_object_query_mux_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_query_object_query_mux_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int charger_send_object_pack(
    uint8_t *dst_p,
    const struct charger_send_object_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->send_mux, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->send_mux, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->byte_value_0x01, 0u, 0xffu);

    switch (src_p->send_mux) {

    case 171:
        break;

    case 402:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_remote_on_off, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_remote_on_off, 0u, 0xffu);
        break;

    case 405:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_dc_output, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_dc_output, 0u, 0xffu);
        break;

    case 407:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_dc_after_pf_alarm, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_dc_after_pf_alarm, 0u, 0xffu);
        break;

    case 408:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_dc_after_power_on, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_dc_after_power_on, 0u, 0xffu);
        break;

    case 410:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_restart, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_restart, 0u, 0xffu);
        break;

    case 411:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_ack_alarms, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_ack_alarms, 0u, 0xffu);
        break;

    case 416:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_ai_vref, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_ai_vref, 0u, 0xffu);
        break;

    case 417:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_ai_rem_sb_level, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_ai_rem_sb_level, 0u, 0xffu);
        break;

    case 418:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_ai_rem_sb_action, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_ai_rem_sb_action, 0u, 0xffu);
        break;

    case 425:
        dst_p[3] |= pack_right_shift_u16(src_p->send_coil_dc_after_remote, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_coil_dc_after_remote, 0u, 0xffu);
        break;

    case 500:
        dst_p[3] |= pack_right_shift_u16(src_p->send_voltage, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_voltage, 0u, 0xffu);
        break;

    case 501:
        dst_p[3] |= pack_right_shift_u16(src_p->send_current, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_current, 0u, 0xffu);
        break;

    case 502:
        dst_p[3] |= pack_right_shift_u16(src_p->send_power, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_power, 0u, 0xffu);
        break;

    case 550:
        dst_p[3] |= pack_right_shift_u16(src_p->send_protection_ovp, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_protection_ovp, 0u, 0xffu);
        break;

    case 553:
        dst_p[3] |= pack_right_shift_u16(src_p->send_protection_ocp, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_protection_ocp, 0u, 0xffu);
        break;

    case 556:
        dst_p[3] |= pack_right_shift_u16(src_p->send_protection_opp, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_protection_opp, 0u, 0xffu);
        break;

    case 650:
        dst_p[3] |= pack_right_shift_u16(src_p->send_ms_coil_link_mode, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_ms_coil_link_mode, 0u, 0xffu);
        break;

    case 653:
        dst_p[3] |= pack_right_shift_u16(src_p->send_ms_coil_enable_ms, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_ms_coil_enable_ms, 0u, 0xffu);
        break;

    case 654:
        dst_p[3] |= pack_right_shift_u16(src_p->send_ms_coil_init_ms, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_ms_coil_init_ms, 0u, 0xffu);
        break;

    case 666:
        dst_p[3] |= pack_right_shift_u16(src_p->send_ms_coil_termination, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_ms_coil_termination, 0u, 0xffu);
        break;

    case 667:
        dst_p[3] |= pack_right_shift_u16(src_p->send_ms_coil_termination_bias, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_ms_coil_termination_bias, 0u, 0xffu);
        break;

    case 9000:
        dst_p[3] |= pack_right_shift_u16(src_p->send_limit_umax, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_limit_umax, 0u, 0xffu);
        break;

    case 9001:
        dst_p[3] |= pack_right_shift_u16(src_p->send_limit_umin, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_limit_umin, 0u, 0xffu);
        break;

    case 9002:
        dst_p[3] |= pack_right_shift_u16(src_p->send_limit_imax, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_limit_imax, 0u, 0xffu);
        break;

    case 9003:
        dst_p[3] |= pack_right_shift_u16(src_p->send_limit_imin, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_limit_imin, 0u, 0xffu);
        break;

    case 9004:
        dst_p[3] |= pack_right_shift_u16(src_p->send_limit_pmax, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(src_p->send_limit_pmax, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int charger_send_object_unpack(
    struct charger_send_object_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->send_mux = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->send_mux |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->byte_value_0x01 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    switch (dst_p->send_mux) {

    case 171:
        break;

    case 402:
        dst_p->send_coil_remote_on_off = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_remote_on_off |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 405:
        dst_p->send_coil_dc_output = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_dc_output |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 407:
        dst_p->send_coil_dc_after_pf_alarm = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_dc_after_pf_alarm |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 408:
        dst_p->send_coil_dc_after_power_on = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_dc_after_power_on |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 410:
        dst_p->send_coil_restart = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_restart |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 411:
        dst_p->send_coil_ack_alarms = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_ack_alarms |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 416:
        dst_p->send_coil_ai_vref = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_ai_vref |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 417:
        dst_p->send_coil_ai_rem_sb_level = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_ai_rem_sb_level |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 418:
        dst_p->send_coil_ai_rem_sb_action = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_ai_rem_sb_action |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 425:
        dst_p->send_coil_dc_after_remote = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_coil_dc_after_remote |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 500:
        dst_p->send_voltage = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_voltage |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 501:
        dst_p->send_current = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_current |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 502:
        dst_p->send_power = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_power |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 550:
        dst_p->send_protection_ovp = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_protection_ovp |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 553:
        dst_p->send_protection_ocp = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_protection_ocp |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 556:
        dst_p->send_protection_opp = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_protection_opp |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 650:
        dst_p->send_ms_coil_link_mode = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_ms_coil_link_mode |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 653:
        dst_p->send_ms_coil_enable_ms = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_ms_coil_enable_ms |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 654:
        dst_p->send_ms_coil_init_ms = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_ms_coil_init_ms |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 666:
        dst_p->send_ms_coil_termination = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_ms_coil_termination |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 667:
        dst_p->send_ms_coil_termination_bias = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_ms_coil_termination_bias |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 9000:
        dst_p->send_limit_umax = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_limit_umax |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 9001:
        dst_p->send_limit_umin = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_limit_umin |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 9002:
        dst_p->send_limit_imax = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_limit_imax |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 9003:
        dst_p->send_limit_imin = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_limit_imin |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    case 9004:
        dst_p->send_limit_pmax = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        dst_p->send_limit_pmax |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

int charger_send_object_init(struct charger_send_object_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_send_object_t));

    return 0;
}

uint16_t charger_send_object_send_mux_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_mux_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_mux_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t charger_send_object_byte_value_0x01_encode(float value)
{
    return (uint8_t)(value);
}

float charger_send_object_byte_value_0x01_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_send_object_byte_value_0x01_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 1u));
}

uint16_t charger_send_object_send_ms_coil_termination_bias_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_ms_coil_termination_bias_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_ms_coil_termination_bias_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_ms_coil_termination_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_ms_coil_termination_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_ms_coil_termination_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_dc_after_remote_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_dc_after_remote_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_dc_after_remote_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_ms_coil_link_mode_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_ms_coil_link_mode_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_ms_coil_link_mode_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_ms_coil_init_ms_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_ms_coil_init_ms_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_ms_coil_init_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_ms_coil_enable_ms_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_ms_coil_enable_ms_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_ms_coil_enable_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_restart_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_restart_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_restart_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_dc_after_power_on_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_dc_after_power_on_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_dc_after_power_on_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_dc_after_pf_alarm_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_dc_after_pf_alarm_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_dc_after_pf_alarm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_ai_vref_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_ai_vref_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_ai_vref_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_ai_rem_sb_level_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_ai_rem_sb_level_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_ai_rem_sb_level_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_ai_rem_sb_action_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_ai_rem_sb_action_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_ai_rem_sb_action_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_ack_alarms_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_ack_alarms_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_ack_alarms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_limit_imin_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_send_object_send_limit_imin_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_send_object_send_limit_imin_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_send_object_send_limit_imax_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_send_object_send_limit_imax_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_send_object_send_limit_imax_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_send_object_send_limit_pmax_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_send_object_send_limit_pmax_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_send_object_send_limit_pmax_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_send_object_send_limit_umin_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_send_object_send_limit_umin_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_send_object_send_limit_umin_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_send_object_send_limit_umax_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_send_object_send_limit_umax_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_send_object_send_limit_umax_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_send_object_send_protection_ovp_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_send_object_send_protection_ovp_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_send_object_send_protection_ovp_is_in_range(uint16_t value)
{
    return (value <= 57671u);
}

uint16_t charger_send_object_send_protection_opp_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_send_object_send_protection_opp_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_send_object_send_protection_opp_is_in_range(uint16_t value)
{
    return (value <= 57671u);
}

uint16_t charger_send_object_send_protection_ocp_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_send_object_send_protection_ocp_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_send_object_send_protection_ocp_is_in_range(uint16_t value)
{
    return (value <= 57671u);
}

uint16_t charger_send_object_send_current_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_send_object_send_current_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_send_object_send_current_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_send_object_send_voltage_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_send_object_send_voltage_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_send_object_send_voltage_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_send_object_send_power_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_send_object_send_power_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_send_object_send_power_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_send_object_send_coil_remote_on_off_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_remote_on_off_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_remote_on_off_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t charger_send_object_send_coil_dc_output_encode(float value)
{
    return (uint16_t)(value);
}

float charger_send_object_send_coil_dc_output_decode(uint16_t value)
{
    return ((float)value);
}

bool charger_send_object_send_coil_dc_output_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int charger_cyclic_read_set_values_pack(
    uint8_t *dst_p,
    const struct charger_cyclic_read_set_values_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->read_voltage_cyclic, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->read_voltage_cyclic, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->read_current_cyclic, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->read_current_cyclic, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->read_power_cyclic, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->read_power_cyclic, 0u, 0xffu);

    return (8);
}

int charger_cyclic_read_set_values_unpack(
    struct charger_cyclic_read_set_values_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->read_voltage_cyclic = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->read_voltage_cyclic |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->read_current_cyclic = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->read_current_cyclic |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->read_power_cyclic = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->read_power_cyclic |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int charger_cyclic_read_set_values_init(struct charger_cyclic_read_set_values_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_cyclic_read_set_values_t));

    return 0;
}

uint16_t charger_cyclic_read_set_values_read_voltage_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_cyclic_read_set_values_read_voltage_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_cyclic_read_set_values_read_voltage_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_cyclic_read_set_values_read_current_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_cyclic_read_set_values_read_current_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_cyclic_read_set_values_read_current_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_cyclic_read_set_values_read_power_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_cyclic_read_set_values_read_power_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_cyclic_read_set_values_read_power_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

int charger_cyclic_read_limits_2_pack(
    uint8_t *dst_p,
    const struct charger_cyclic_read_limits_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->read_limit_pmax_cyclic, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->read_limit_pmax_cyclic, 0u, 0xffu);

    return (8);
}

int charger_cyclic_read_limits_2_unpack(
    struct charger_cyclic_read_limits_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->read_limit_pmax_cyclic = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->read_limit_pmax_cyclic |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);

    return (0);
}

int charger_cyclic_read_limits_2_init(struct charger_cyclic_read_limits_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_cyclic_read_limits_2_t));

    return 0;
}

uint16_t charger_cyclic_read_limits_2_read_limit_pmax_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_cyclic_read_limits_2_read_limit_pmax_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_cyclic_read_limits_2_read_limit_pmax_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

int charger_cyclic_read_limits_1_pack(
    uint8_t *dst_p,
    const struct charger_cyclic_read_limits_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->read_limit_imax_cyclic, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->read_limit_imax_cyclic, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->read_limit_imin_cyclic, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->read_limit_imin_cyclic, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->read_limit_umax_cyclic, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->read_limit_umax_cyclic, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->read_limit_umin_cyclic, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->read_limit_umin_cyclic, 0u, 0xffu);

    return (8);
}

int charger_cyclic_read_limits_1_unpack(
    struct charger_cyclic_read_limits_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->read_limit_imax_cyclic = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->read_limit_imax_cyclic |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->read_limit_imin_cyclic = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->read_limit_imin_cyclic |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->read_limit_umax_cyclic = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->read_limit_umax_cyclic |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->read_limit_umin_cyclic = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->read_limit_umin_cyclic |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int charger_cyclic_read_limits_1_init(struct charger_cyclic_read_limits_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_cyclic_read_limits_1_t));

    return 0;
}

uint16_t charger_cyclic_read_limits_1_read_limit_imax_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_cyclic_read_limits_1_read_limit_imax_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_cyclic_read_limits_1_read_limit_imax_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_cyclic_read_limits_1_read_limit_imin_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_cyclic_read_limits_1_read_limit_imin_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_cyclic_read_limits_1_read_limit_imin_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_cyclic_read_limits_1_read_limit_umax_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_cyclic_read_limits_1_read_limit_umax_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_cyclic_read_limits_1_read_limit_umax_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_cyclic_read_limits_1_read_limit_umin_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_cyclic_read_limits_1_read_limit_umin_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_cyclic_read_limits_1_read_limit_umin_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

int charger_cyclic_read_status_pack(
    uint8_t *dst_p,
    const struct charger_cyclic_read_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->read_status_remote_cyclic, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->read_coil_dc_output_cyclic, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->read_status_alarms_cyclic, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->read_status_alarm_mss_cyclic, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->read_status_alarm_ocp_cyclic, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->read_status_access_cyclic, 3u, 0xf8u);
    dst_p[1] |= pack_left_shift_u8(src_p->read_status_alarm_opp_cyclic, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->read_status_alarm_ot_cyclic, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->read_status_alarm_ovp_cyclic, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->read_status_alarm_pf_cyclic, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->read_status_alarm_rem_sb_cyclic, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->read_status_ext_sense_cyclic, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->read_status_ms_type_cyclic, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->read_status_dc_output_cyclic, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->read_status_reg_act_cyclic, 1u, 0x06u);

    return (8);
}

int charger_cyclic_read_status_unpack(
    struct charger_cyclic_read_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->read_status_remote_cyclic = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->read_coil_dc_output_cyclic = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->read_status_alarms_cyclic = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->read_status_alarm_mss_cyclic = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->read_status_alarm_ocp_cyclic = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->read_status_access_cyclic = unpack_right_shift_u8(src_p[1], 3u, 0xf8u);
    dst_p->read_status_alarm_opp_cyclic = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->read_status_alarm_ot_cyclic = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->read_status_alarm_ovp_cyclic = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->read_status_alarm_pf_cyclic = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->read_status_alarm_rem_sb_cyclic = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->read_status_ext_sense_cyclic = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->read_status_ms_type_cyclic = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->read_status_dc_output_cyclic = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->read_status_reg_act_cyclic = unpack_right_shift_u8(src_p[3], 1u, 0x06u);

    return (0);
}

int charger_cyclic_read_status_init(struct charger_cyclic_read_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_cyclic_read_status_t));

    return 0;
}

uint8_t charger_cyclic_read_status_read_status_remote_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_remote_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_remote_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_coil_dc_output_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_coil_dc_output_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_coil_dc_output_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_alarms_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarms_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarms_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_alarm_mss_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarm_mss_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarm_mss_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_alarm_ocp_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarm_ocp_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarm_ocp_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_access_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_access_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_access_cyclic_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t charger_cyclic_read_status_read_status_alarm_opp_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarm_opp_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarm_opp_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_alarm_ot_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarm_ot_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarm_ot_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_alarm_ovp_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarm_ovp_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarm_ovp_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_alarm_pf_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarm_pf_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarm_pf_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_alarm_rem_sb_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_alarm_rem_sb_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_alarm_rem_sb_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_ext_sense_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_ext_sense_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_ext_sense_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_ms_type_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_ms_type_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_ms_type_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_dc_output_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_dc_output_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_dc_output_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_read_status_read_status_reg_act_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_read_status_read_status_reg_act_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_read_status_read_status_reg_act_cyclic_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int charger_cyclic_read_act_values_pack(
    uint8_t *dst_p,
    const struct charger_cyclic_read_act_values_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->read_actual_voltage_cyclic, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->read_actual_voltage_cyclic, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->read_actual_current_cyclic, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->read_actual_current_cyclic, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->read_actual_power_cyclic, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->read_actual_power_cyclic, 0u, 0xffu);

    return (8);
}

int charger_cyclic_read_act_values_unpack(
    struct charger_cyclic_read_act_values_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->read_actual_voltage_cyclic = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->read_actual_voltage_cyclic |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->read_actual_current_cyclic = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->read_actual_current_cyclic |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->read_actual_power_cyclic = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->read_actual_power_cyclic |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int charger_cyclic_read_act_values_init(struct charger_cyclic_read_act_values_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_cyclic_read_act_values_t));

    return 0;
}

uint16_t charger_cyclic_read_act_values_read_actual_voltage_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_cyclic_read_act_values_read_actual_voltage_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_cyclic_read_act_values_read_actual_voltage_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_cyclic_read_act_values_read_actual_current_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_cyclic_read_act_values_read_actual_current_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_cyclic_read_act_values_read_actual_current_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_cyclic_read_act_values_read_actual_power_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_cyclic_read_act_values_read_actual_power_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_cyclic_read_act_values_read_actual_power_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

int charger_cyclic_send_mode_pack(
    uint8_t *dst_p,
    const struct charger_cyclic_send_mode_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->send_coil_ack_alarms_cyclic, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->send_coil_dc_output_cyclic, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->send_coil_remote_on_off_cyclic, 0u, 0x01u);

    return (8);
}

int charger_cyclic_send_mode_unpack(
    struct charger_cyclic_send_mode_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->send_coil_ack_alarms_cyclic = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->send_coil_dc_output_cyclic = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->send_coil_remote_on_off_cyclic = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int charger_cyclic_send_mode_init(struct charger_cyclic_send_mode_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_cyclic_send_mode_t));

    return 0;
}

uint8_t charger_cyclic_send_mode_send_coil_ack_alarms_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_send_mode_send_coil_ack_alarms_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_send_mode_send_coil_ack_alarms_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_send_mode_send_coil_dc_output_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_send_mode_send_coil_dc_output_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_send_mode_send_coil_dc_output_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t charger_cyclic_send_mode_send_coil_remote_on_off_cyclic_encode(float value)
{
    return (uint8_t)(value);
}

float charger_cyclic_send_mode_send_coil_remote_on_off_cyclic_decode(uint8_t value)
{
    return ((float)value);
}

bool charger_cyclic_send_mode_send_coil_remote_on_off_cyclic_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int charger_cyclic_send_set_values_pack(
    uint8_t *dst_p,
    const struct charger_cyclic_send_set_values_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->send_voltage_cyclic, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->send_voltage_cyclic, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->send_current_cyclic, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->send_current_cyclic, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->send_power_cyclic, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->send_power_cyclic, 0u, 0xffu);

    return (8);
}

int charger_cyclic_send_set_values_unpack(
    struct charger_cyclic_send_set_values_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->send_voltage_cyclic = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->send_voltage_cyclic |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->send_current_cyclic = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->send_current_cyclic |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->send_power_cyclic = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->send_power_cyclic |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

int charger_cyclic_send_set_values_init(struct charger_cyclic_send_set_values_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct charger_cyclic_send_set_values_t));

    return 0;
}

uint16_t charger_cyclic_send_set_values_send_voltage_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.014305333f);
}

float charger_cyclic_send_set_values_send_voltage_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.014305333f);
}

bool charger_cyclic_send_set_values_send_voltage_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}

uint16_t charger_cyclic_send_set_values_send_current_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.000381476f);
}

float charger_cyclic_send_set_values_send_current_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.000381476f);
}

bool charger_cyclic_send_set_values_send_current_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53476u);
}

uint16_t charger_cyclic_send_set_values_send_power_cyclic_encode(float value)
{
    return (uint16_t)(value / 0.095368887f);
}

float charger_cyclic_send_set_values_send_power_cyclic_decode(uint16_t value)
{
    return ((float)value * 0.095368887f);
}

bool charger_cyclic_send_set_values_send_power_cyclic_is_in_range(uint16_t value)
{
    return (value <= 53477u);
}
