/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Wed Jul 29 16:41:49 2026.
 */

#include <string.h>

#include "inverter.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int inverter_emcu_state_9_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_9_left_t *src_p,
    size_t size)
{
    uint16_t torque_est_nm;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->e2_e_p1_crc, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_zero, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_cnt, 4u, 0xf0u);
    torque_est_nm = (uint16_t)src_p->torque_est_nm;
    dst_p[2] |= pack_left_shift_u16(torque_est_nm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(torque_est_nm, 8u, 0xffu);

    return (4);
}

int inverter_emcu_state_9_left_unpack(
    struct inverter_emcu_state_9_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t torque_est_nm;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->e2_e_p1_crc = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->e2_e_p1_zero = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->e2_e_p1_cnt = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    torque_est_nm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    torque_est_nm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_est_nm = (int16_t)torque_est_nm;

    return (0);
}

int inverter_emcu_state_9_left_init(struct inverter_emcu_state_9_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_9_left_t));

    return 0;
}

uint8_t inverter_emcu_state_9_left_e2_e_p1_crc_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_9_left_e2_e_p1_crc_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_left_e2_e_p1_crc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_state_9_left_e2_e_p1_zero_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_9_left_e2_e_p1_zero_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_left_e2_e_p1_zero_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_state_9_left_e2_e_p1_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_9_left_e2_e_p1_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_left_e2_e_p1_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int16_t inverter_emcu_state_9_left_torque_est_nm_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_9_left_torque_est_nm_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_left_torque_est_nm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_8_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_8_left_t *src_p,
    size_t size)
{
    uint16_t setpoint_app_d_a;
    uint16_t setpoint_app_q_a;
    uint16_t torque_max_feas_ndm;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    torque_max_feas_ndm = (uint16_t)src_p->torque_max_feas_ndm;
    dst_p[0] |= pack_left_shift_u16(torque_max_feas_ndm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(torque_max_feas_ndm, 8u, 0xffu);
    setpoint_app_d_a = (uint16_t)src_p->setpoint_app_d_a;
    dst_p[2] |= pack_left_shift_u16(setpoint_app_d_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(setpoint_app_d_a, 8u, 0xffu);
    setpoint_app_q_a = (uint16_t)src_p->setpoint_app_q_a;
    dst_p[4] |= pack_left_shift_u16(setpoint_app_q_a, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(setpoint_app_q_a, 8u, 0xffu);

    return (6);
}

int inverter_emcu_state_8_left_unpack(
    struct inverter_emcu_state_8_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint_app_d_a;
    uint16_t setpoint_app_q_a;
    uint16_t torque_max_feas_ndm;

    if (size < 6u) {
        return (-EINVAL);
    }

    torque_max_feas_ndm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    torque_max_feas_ndm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->torque_max_feas_ndm = (int16_t)torque_max_feas_ndm;
    setpoint_app_d_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    setpoint_app_d_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->setpoint_app_d_a = (int16_t)setpoint_app_d_a;
    setpoint_app_q_a = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    setpoint_app_q_a |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->setpoint_app_q_a = (int16_t)setpoint_app_q_a;

    return (0);
}

int inverter_emcu_state_8_left_init(struct inverter_emcu_state_8_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_8_left_t));

    return 0;
}

int16_t inverter_emcu_state_8_left_torque_max_feas_ndm_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_8_left_torque_max_feas_ndm_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_8_left_torque_max_feas_ndm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_8_left_setpoint_app_d_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_8_left_setpoint_app_d_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_8_left_setpoint_app_d_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_8_left_setpoint_app_q_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_8_left_setpoint_app_q_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_8_left_setpoint_app_q_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_7_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_7_left_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->dem, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->dem, 8u, 0xffu);

    return (2);
}

int inverter_emcu_state_7_left_unpack(
    struct inverter_emcu_state_7_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->dem = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->dem |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int inverter_emcu_state_7_left_init(struct inverter_emcu_state_7_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_7_left_t));

    return 0;
}

uint16_t inverter_emcu_state_7_left_dem_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_7_left_dem_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_7_left_dem_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_6_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_6_left_t *src_p,
    size_t size)
{
    uint16_t ac_bus_power_w;
    uint16_t ac_bus_voltage_v;
    uint16_t dc_bus_power_w;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->dc_bus_voltage_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->dc_bus_voltage_v, 8u, 0x03u);
    ac_bus_power_w = (uint16_t)src_p->ac_bus_power_w;
    dst_p[1] |= pack_left_shift_u16(ac_bus_power_w, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(ac_bus_power_w, 6u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(ac_bus_power_w, 14u, 0x03u);
    dc_bus_power_w = (uint16_t)src_p->dc_bus_power_w;
    dst_p[4] |= pack_left_shift_u16(dc_bus_power_w, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(dc_bus_power_w, 8u, 0xffu);
    ac_bus_voltage_v = (uint16_t)src_p->ac_bus_voltage_v;
    dst_p[6] |= pack_left_shift_u16(ac_bus_voltage_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(ac_bus_voltage_v, 8u, 0xffu);

    return (8);
}

int inverter_emcu_state_6_left_unpack(
    struct inverter_emcu_state_6_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t ac_bus_power_w;
    uint16_t ac_bus_voltage_v;
    uint16_t dc_bus_power_w;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->dc_bus_voltage_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->dc_bus_voltage_v |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    ac_bus_power_w = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    ac_bus_power_w |= unpack_left_shift_u16(src_p[2], 6u, 0xffu);
    ac_bus_power_w |= unpack_left_shift_u16(src_p[3], 14u, 0x03u);
    dst_p->ac_bus_power_w = (int16_t)ac_bus_power_w;
    dc_bus_power_w = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dc_bus_power_w |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->dc_bus_power_w = (int16_t)dc_bus_power_w;
    ac_bus_voltage_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    ac_bus_voltage_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->ac_bus_voltage_v = (int16_t)ac_bus_voltage_v;

    return (0);
}

int inverter_emcu_state_6_left_init(struct inverter_emcu_state_6_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_6_left_t));

    return 0;
}

uint16_t inverter_emcu_state_6_left_dc_bus_voltage_v_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_6_left_dc_bus_voltage_v_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_6_left_dc_bus_voltage_v_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int16_t inverter_emcu_state_6_left_ac_bus_power_w_encode(float value)
{
    return (int16_t)(value / 32.767f);
}

float inverter_emcu_state_6_left_ac_bus_power_w_decode(int16_t value)
{
    return ((float)value * 32.767f);
}

bool inverter_emcu_state_6_left_ac_bus_power_w_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_6_left_dc_bus_power_w_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_6_left_dc_bus_power_w_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_6_left_dc_bus_power_w_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_6_left_ac_bus_voltage_v_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_6_left_ac_bus_voltage_v_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_6_left_ac_bus_voltage_v_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_5_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_5_left_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd_src_app, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->ctrl_type_app, 3u, 0x38u);
    dst_p[1] |= pack_left_shift_u8(src_p->ctrl_mode_app, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->pos_fb_src_app, 4u, 0xf0u);

    return (2);
}

int inverter_emcu_state_5_left_unpack(
    struct inverter_emcu_state_5_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->cmd_src_app = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->ctrl_type_app = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->ctrl_mode_app = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->pos_fb_src_app = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);

    return (0);
}

int inverter_emcu_state_5_left_init(struct inverter_emcu_state_5_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_5_left_t));

    return 0;
}

uint8_t inverter_emcu_state_5_left_cmd_src_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_left_cmd_src_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_left_cmd_src_app_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t inverter_emcu_state_5_left_ctrl_type_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_left_ctrl_type_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_left_ctrl_type_app_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t inverter_emcu_state_5_left_ctrl_mode_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_left_ctrl_mode_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_left_ctrl_mode_app_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_state_5_left_pos_fb_src_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_left_pos_fb_src_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_left_pos_fb_src_app_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int inverter_emcu_state_4_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_4_left_t *src_p,
    size_t size)
{
    uint8_t board_1_temp_deg_c;
    uint8_t board_2_temp_deg_c;
    uint8_t e_machine_temp_1_deg_c;
    uint8_t e_machine_temp_2_deg_c;
    uint8_t pwr_stg_temp_deg_c;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    board_1_temp_deg_c = (uint8_t)src_p->board_1_temp_deg_c;
    dst_p[0] |= pack_left_shift_u8(board_1_temp_deg_c, 0u, 0xffu);
    board_2_temp_deg_c = (uint8_t)src_p->board_2_temp_deg_c;
    dst_p[1] |= pack_left_shift_u8(board_2_temp_deg_c, 0u, 0xffu);
    pwr_stg_temp_deg_c = (uint8_t)src_p->pwr_stg_temp_deg_c;
    dst_p[2] |= pack_left_shift_u8(pwr_stg_temp_deg_c, 0u, 0xffu);
    e_machine_temp_1_deg_c = (uint8_t)src_p->e_machine_temp_1_deg_c;
    dst_p[3] |= pack_left_shift_u8(e_machine_temp_1_deg_c, 0u, 0xffu);
    e_machine_temp_2_deg_c = (uint8_t)src_p->e_machine_temp_2_deg_c;
    dst_p[4] |= pack_left_shift_u8(e_machine_temp_2_deg_c, 0u, 0xffu);

    return (5);
}

int inverter_emcu_state_4_left_unpack(
    struct inverter_emcu_state_4_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t board_1_temp_deg_c;
    uint8_t board_2_temp_deg_c;
    uint8_t e_machine_temp_1_deg_c;
    uint8_t e_machine_temp_2_deg_c;
    uint8_t pwr_stg_temp_deg_c;

    if (size < 5u) {
        return (-EINVAL);
    }

    board_1_temp_deg_c = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->board_1_temp_deg_c = (int8_t)board_1_temp_deg_c;
    board_2_temp_deg_c = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->board_2_temp_deg_c = (int8_t)board_2_temp_deg_c;
    pwr_stg_temp_deg_c = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->pwr_stg_temp_deg_c = (int8_t)pwr_stg_temp_deg_c;
    e_machine_temp_1_deg_c = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->e_machine_temp_1_deg_c = (int8_t)e_machine_temp_1_deg_c;
    e_machine_temp_2_deg_c = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->e_machine_temp_2_deg_c = (int8_t)e_machine_temp_2_deg_c;

    return (0);
}

int inverter_emcu_state_4_left_init(struct inverter_emcu_state_4_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_4_left_t));

    return 0;
}

int8_t inverter_emcu_state_4_left_board_1_temp_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_left_board_1_temp_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_left_board_1_temp_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_left_board_2_temp_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_left_board_2_temp_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_left_board_2_temp_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_left_pwr_stg_temp_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_left_pwr_stg_temp_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_left_pwr_stg_temp_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_left_e_machine_temp_1_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_left_e_machine_temp_1_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_left_e_machine_temp_1_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_left_e_machine_temp_2_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_left_e_machine_temp_2_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_left_e_machine_temp_2_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_3_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_3_left_t *src_p,
    size_t size)
{
    uint16_t current_d_a;
    uint16_t current_q_a;
    uint32_t e_machine_speed_erpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    current_d_a = (uint16_t)src_p->current_d_a;
    dst_p[0] |= pack_left_shift_u16(current_d_a, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current_d_a, 8u, 0xffu);
    current_q_a = (uint16_t)src_p->current_q_a;
    dst_p[2] |= pack_left_shift_u16(current_q_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_q_a, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->volt_modulus_permil, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->volt_modulus_permil, 8u, 0x0fu);
    e_machine_speed_erpm = (uint32_t)src_p->e_machine_speed_erpm;
    dst_p[5] |= pack_left_shift_u32(e_machine_speed_erpm, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u32(e_machine_speed_erpm, 4u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(e_machine_speed_erpm, 12u, 0xffu);

    return (8);
}

int inverter_emcu_state_3_left_unpack(
    struct inverter_emcu_state_3_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_d_a;
    uint16_t current_q_a;
    uint32_t e_machine_speed_erpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    current_d_a = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current_d_a |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current_d_a = (int16_t)current_d_a;
    current_q_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_q_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_q_a = (int16_t)current_q_a;
    dst_p->volt_modulus_permil = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->volt_modulus_permil |= unpack_left_shift_u16(src_p[5], 8u, 0x0fu);
    e_machine_speed_erpm = unpack_right_shift_u32(src_p[5], 4u, 0xf0u);
    e_machine_speed_erpm |= unpack_left_shift_u32(src_p[6], 4u, 0xffu);
    e_machine_speed_erpm |= unpack_left_shift_u32(src_p[7], 12u, 0xffu);

    if ((e_machine_speed_erpm & (1u << 19)) != 0u) {
        e_machine_speed_erpm |= 0xfff00000u;
    }

    dst_p->e_machine_speed_erpm = (int32_t)e_machine_speed_erpm;

    return (0);
}

int inverter_emcu_state_3_left_init(struct inverter_emcu_state_3_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_3_left_t));

    return 0;
}

int16_t inverter_emcu_state_3_left_current_d_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_3_left_current_d_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_3_left_current_d_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_3_left_current_q_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_3_left_current_q_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_3_left_current_q_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t inverter_emcu_state_3_left_volt_modulus_permil_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_3_left_volt_modulus_permil_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_3_left_volt_modulus_permil_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int32_t inverter_emcu_state_3_left_e_machine_speed_erpm_encode(float value)
{
    return (int32_t)(value);
}

float inverter_emcu_state_3_left_e_machine_speed_erpm_decode(int32_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_3_left_e_machine_speed_erpm_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}

int inverter_emcu_state_2_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_2_left_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u16(src_p->pwr_stg_bit_state, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pwr_stg_bit_state, 8u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->em_ctrl_foc_bit_state, 1u, 0xfeu);
    dst_p[2] |= pack_right_shift_u8(src_p->em_ctrl_foc_bit_state, 7u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->app_state_app, 1u, 0xfeu);

    return (3);
}

int inverter_emcu_state_2_left_unpack(
    struct inverter_emcu_state_2_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->pwr_stg_bit_state = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pwr_stg_bit_state |= unpack_left_shift_u16(src_p[1], 8u, 0x01u);
    dst_p->em_ctrl_foc_bit_state = unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->em_ctrl_foc_bit_state |= unpack_left_shift_u8(src_p[2], 7u, 0x01u);
    dst_p->app_state_app = unpack_right_shift_u8(src_p[2], 1u, 0xfeu);

    return (0);
}

int inverter_emcu_state_2_left_init(struct inverter_emcu_state_2_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_2_left_t));

    return 0;
}

uint16_t inverter_emcu_state_2_left_pwr_stg_bit_state_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_2_left_pwr_stg_bit_state_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_2_left_pwr_stg_bit_state_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

uint8_t inverter_emcu_state_2_left_em_ctrl_foc_bit_state_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_2_left_em_ctrl_foc_bit_state_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_2_left_em_ctrl_foc_bit_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_state_2_left_app_state_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_2_left_app_state_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_2_left_app_state_app_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

int inverter_emcu_state_1_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_1_left_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u32(src_p->uptime_ms, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->uptime_ms, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->uptime_ms, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->uptime_ms, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->cpu_load, 0u, 0xffu);

    return (5);
}

int inverter_emcu_state_1_left_unpack(
    struct inverter_emcu_state_1_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->uptime_ms = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->cpu_load = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int inverter_emcu_state_1_left_init(struct inverter_emcu_state_1_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_1_left_t));

    return 0;
}

uint32_t inverter_emcu_state_1_left_uptime_ms_encode(float value)
{
    return (uint32_t)(value);
}

float inverter_emcu_state_1_left_uptime_ms_decode(uint32_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_1_left_uptime_ms_is_in_range(uint32_t value)
{
    return (value <= 2704u);
}

uint8_t inverter_emcu_state_1_left_cpu_load_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_1_left_cpu_load_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_1_left_cpu_load_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_6_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_6_left_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->pwm_freq_k_hz, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pwm_freq_k_hz, 8u, 0xffu);

    return (2);
}

int inverter_emcu_setpoint_6_left_unpack(
    struct inverter_emcu_setpoint_6_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->pwm_freq_k_hz = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pwm_freq_k_hz |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int inverter_emcu_setpoint_6_left_init(struct inverter_emcu_setpoint_6_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_6_left_t));

    return 0;
}

uint16_t inverter_emcu_setpoint_6_left_pwm_freq_k_hz_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_setpoint_6_left_pwm_freq_k_hz_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_6_left_pwm_freq_k_hz_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_4_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_4_left_t *src_p,
    size_t size)
{
    uint32_t speed_erpm;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    speed_erpm = (uint32_t)src_p->speed_erpm;
    dst_p[0] |= pack_left_shift_u32(speed_erpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(speed_erpm, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(speed_erpm, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(speed_erpm, 24u, 0xffu);

    return (4);
}

int inverter_emcu_setpoint_4_left_unpack(
    struct inverter_emcu_setpoint_4_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t speed_erpm;

    if (size < 4u) {
        return (-EINVAL);
    }

    speed_erpm = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    speed_erpm |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    speed_erpm |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    speed_erpm |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->speed_erpm = (int32_t)speed_erpm;

    return (0);
}

int inverter_emcu_setpoint_4_left_init(struct inverter_emcu_setpoint_4_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_4_left_t));

    return 0;
}

int32_t inverter_emcu_setpoint_4_left_speed_erpm_encode(float value)
{
    return (int32_t)(value);
}

float inverter_emcu_setpoint_4_left_speed_erpm_decode(int32_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_4_left_speed_erpm_is_in_range(int32_t value)
{
    return ((value >= -2147480000) && (value <= 2147480000));
}

int inverter_emcu_setpoint_3_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_3_left_t *src_p,
    size_t size)
{
    uint16_t torque_nm_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->e2_e_p1_crc, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_zero, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_cnt, 4u, 0xf0u);
    torque_nm_req = (uint16_t)src_p->torque_nm_req;
    dst_p[2] |= pack_left_shift_u16(torque_nm_req, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(torque_nm_req, 8u, 0xffu);

    return (4);
}

int inverter_emcu_setpoint_3_left_unpack(
    struct inverter_emcu_setpoint_3_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t torque_nm_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->e2_e_p1_crc = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->e2_e_p1_zero = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->e2_e_p1_cnt = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    torque_nm_req = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    torque_nm_req |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_nm_req = (int16_t)torque_nm_req;

    return (0);
}

int inverter_emcu_setpoint_3_left_init(struct inverter_emcu_setpoint_3_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_3_left_t));

    return 0;
}

uint8_t inverter_emcu_setpoint_3_left_e2_e_p1_crc_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_3_left_e2_e_p1_crc_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_left_e2_e_p1_crc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_setpoint_3_left_e2_e_p1_zero_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_3_left_e2_e_p1_zero_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_left_e2_e_p1_zero_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_setpoint_3_left_e2_e_p1_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_3_left_e2_e_p1_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_left_e2_e_p1_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int16_t inverter_emcu_setpoint_3_left_torque_nm_req_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_setpoint_3_left_torque_nm_req_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_left_torque_nm_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_2_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_2_left_t *src_p,
    size_t size)
{
    uint16_t current_d_a_req;
    uint16_t current_q_a_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    current_d_a_req = (uint16_t)src_p->current_d_a_req;
    dst_p[0] |= pack_left_shift_u16(current_d_a_req, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current_d_a_req, 8u, 0xffu);
    current_q_a_req = (uint16_t)src_p->current_q_a_req;
    dst_p[2] |= pack_left_shift_u16(current_q_a_req, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_q_a_req, 8u, 0xffu);

    return (4);
}

int inverter_emcu_setpoint_2_left_unpack(
    struct inverter_emcu_setpoint_2_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_d_a_req;
    uint16_t current_q_a_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    current_d_a_req = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current_d_a_req |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current_d_a_req = (int16_t)current_d_a_req;
    current_q_a_req = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_q_a_req |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_q_a_req = (int16_t)current_q_a_req;

    return (0);
}

int inverter_emcu_setpoint_2_left_init(struct inverter_emcu_setpoint_2_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_2_left_t));

    return 0;
}

int16_t inverter_emcu_setpoint_2_left_current_d_a_req_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_setpoint_2_left_current_d_a_req_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_setpoint_2_left_current_d_a_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_setpoint_2_left_current_q_a_req_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_setpoint_2_left_current_q_a_req_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_setpoint_2_left_current_q_a_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_1_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_1_left_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->e2_e_p1_crc, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_zero, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_cnt, 4u, 0xf0u);
    dst_p[2] |= pack_left_shift_u8(src_p->app_state_req, 0u, 0xffu);

    return (3);
}

int inverter_emcu_setpoint_1_left_unpack(
    struct inverter_emcu_setpoint_1_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->e2_e_p1_crc = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->e2_e_p1_zero = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->e2_e_p1_cnt = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    dst_p->app_state_req = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int inverter_emcu_setpoint_1_left_init(struct inverter_emcu_setpoint_1_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_1_left_t));

    return 0;
}

uint8_t inverter_emcu_setpoint_1_left_e2_e_p1_crc_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_left_e2_e_p1_crc_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_left_e2_e_p1_crc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_setpoint_1_left_e2_e_p1_zero_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_left_e2_e_p1_zero_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_left_e2_e_p1_zero_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_setpoint_1_left_e2_e_p1_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_left_e2_e_p1_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_left_e2_e_p1_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_setpoint_1_left_app_state_req_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_left_app_state_req_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_left_app_state_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_debug_1_left_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_debug_1_left_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->e_machine_angle_fract16, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->e_machine_angle_fract16, 8u, 0xffu);

    return (2);
}

int inverter_emcu_debug_1_left_unpack(
    struct inverter_emcu_debug_1_left_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->e_machine_angle_fract16 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->e_machine_angle_fract16 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int inverter_emcu_debug_1_left_init(struct inverter_emcu_debug_1_left_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_debug_1_left_t));

    return 0;
}

uint16_t inverter_emcu_debug_1_left_e_machine_angle_fract16_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_debug_1_left_e_machine_angle_fract16_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_debug_1_left_e_machine_angle_fract16_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_1_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_1_right_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u32(src_p->uptime_ms, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->uptime_ms, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->uptime_ms, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->uptime_ms, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->cpu_load, 0u, 0xffu);

    return (5);
}

int inverter_emcu_state_1_right_unpack(
    struct inverter_emcu_state_1_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->uptime_ms = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->uptime_ms |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->cpu_load = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int inverter_emcu_state_1_right_init(struct inverter_emcu_state_1_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_1_right_t));

    return 0;
}

uint32_t inverter_emcu_state_1_right_uptime_ms_encode(float value)
{
    return (uint32_t)(value);
}

float inverter_emcu_state_1_right_uptime_ms_decode(uint32_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_1_right_uptime_ms_is_in_range(uint32_t value)
{
    return (value <= 2704u);
}

uint8_t inverter_emcu_state_1_right_cpu_load_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_1_right_cpu_load_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_1_right_cpu_load_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_2_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_2_right_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u16(src_p->pwr_stg_bit_state, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pwr_stg_bit_state, 8u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->em_ctrl_foc_bit_state, 1u, 0xfeu);
    dst_p[2] |= pack_right_shift_u8(src_p->em_ctrl_foc_bit_state, 7u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->app_state_app, 1u, 0xfeu);

    return (3);
}

int inverter_emcu_state_2_right_unpack(
    struct inverter_emcu_state_2_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->pwr_stg_bit_state = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pwr_stg_bit_state |= unpack_left_shift_u16(src_p[1], 8u, 0x01u);
    dst_p->em_ctrl_foc_bit_state = unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->em_ctrl_foc_bit_state |= unpack_left_shift_u8(src_p[2], 7u, 0x01u);
    dst_p->app_state_app = unpack_right_shift_u8(src_p[2], 1u, 0xfeu);

    return (0);
}

int inverter_emcu_state_2_right_init(struct inverter_emcu_state_2_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_2_right_t));

    return 0;
}

uint16_t inverter_emcu_state_2_right_pwr_stg_bit_state_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_2_right_pwr_stg_bit_state_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_2_right_pwr_stg_bit_state_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

uint8_t inverter_emcu_state_2_right_em_ctrl_foc_bit_state_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_2_right_em_ctrl_foc_bit_state_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_2_right_em_ctrl_foc_bit_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_state_2_right_app_state_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_2_right_app_state_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_2_right_app_state_app_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

int inverter_emcu_state_3_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_3_right_t *src_p,
    size_t size)
{
    uint16_t current_d_a;
    uint16_t current_q_a;
    uint32_t e_machine_speed_erpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    current_d_a = (uint16_t)src_p->current_d_a;
    dst_p[0] |= pack_left_shift_u16(current_d_a, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current_d_a, 8u, 0xffu);
    current_q_a = (uint16_t)src_p->current_q_a;
    dst_p[2] |= pack_left_shift_u16(current_q_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_q_a, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->volt_modulus_permil, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->volt_modulus_permil, 8u, 0x0fu);
    e_machine_speed_erpm = (uint32_t)src_p->e_machine_speed_erpm;
    dst_p[5] |= pack_left_shift_u32(e_machine_speed_erpm, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u32(e_machine_speed_erpm, 4u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(e_machine_speed_erpm, 12u, 0xffu);

    return (8);
}

int inverter_emcu_state_3_right_unpack(
    struct inverter_emcu_state_3_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_d_a;
    uint16_t current_q_a;
    uint32_t e_machine_speed_erpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    current_d_a = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current_d_a |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current_d_a = (int16_t)current_d_a;
    current_q_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_q_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_q_a = (int16_t)current_q_a;
    dst_p->volt_modulus_permil = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->volt_modulus_permil |= unpack_left_shift_u16(src_p[5], 8u, 0x0fu);
    e_machine_speed_erpm = unpack_right_shift_u32(src_p[5], 4u, 0xf0u);
    e_machine_speed_erpm |= unpack_left_shift_u32(src_p[6], 4u, 0xffu);
    e_machine_speed_erpm |= unpack_left_shift_u32(src_p[7], 12u, 0xffu);

    if ((e_machine_speed_erpm & (1u << 19)) != 0u) {
        e_machine_speed_erpm |= 0xfff00000u;
    }

    dst_p->e_machine_speed_erpm = (int32_t)e_machine_speed_erpm;

    return (0);
}

int inverter_emcu_state_3_right_init(struct inverter_emcu_state_3_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_3_right_t));

    return 0;
}

int16_t inverter_emcu_state_3_right_current_d_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_3_right_current_d_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_3_right_current_d_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_3_right_current_q_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_3_right_current_q_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_3_right_current_q_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t inverter_emcu_state_3_right_volt_modulus_permil_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_3_right_volt_modulus_permil_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_3_right_volt_modulus_permil_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int32_t inverter_emcu_state_3_right_e_machine_speed_erpm_encode(float value)
{
    return (int32_t)(value);
}

float inverter_emcu_state_3_right_e_machine_speed_erpm_decode(int32_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_3_right_e_machine_speed_erpm_is_in_range(int32_t value)
{
    return ((value >= -524288) && (value <= 524287));
}

int inverter_emcu_state_4_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_4_right_t *src_p,
    size_t size)
{
    uint8_t board_1_temp_deg_c;
    uint8_t board_2_temp_deg_c;
    uint8_t e_machine_temp_1_deg_c;
    uint8_t e_machine_temp_2_deg_c;
    uint8_t pwr_stg_temp_deg_c;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    board_1_temp_deg_c = (uint8_t)src_p->board_1_temp_deg_c;
    dst_p[0] |= pack_left_shift_u8(board_1_temp_deg_c, 0u, 0xffu);
    board_2_temp_deg_c = (uint8_t)src_p->board_2_temp_deg_c;
    dst_p[1] |= pack_left_shift_u8(board_2_temp_deg_c, 0u, 0xffu);
    pwr_stg_temp_deg_c = (uint8_t)src_p->pwr_stg_temp_deg_c;
    dst_p[2] |= pack_left_shift_u8(pwr_stg_temp_deg_c, 0u, 0xffu);
    e_machine_temp_1_deg_c = (uint8_t)src_p->e_machine_temp_1_deg_c;
    dst_p[3] |= pack_left_shift_u8(e_machine_temp_1_deg_c, 0u, 0xffu);
    e_machine_temp_2_deg_c = (uint8_t)src_p->e_machine_temp_2_deg_c;
    dst_p[4] |= pack_left_shift_u8(e_machine_temp_2_deg_c, 0u, 0xffu);

    return (5);
}

int inverter_emcu_state_4_right_unpack(
    struct inverter_emcu_state_4_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t board_1_temp_deg_c;
    uint8_t board_2_temp_deg_c;
    uint8_t e_machine_temp_1_deg_c;
    uint8_t e_machine_temp_2_deg_c;
    uint8_t pwr_stg_temp_deg_c;

    if (size < 5u) {
        return (-EINVAL);
    }

    board_1_temp_deg_c = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->board_1_temp_deg_c = (int8_t)board_1_temp_deg_c;
    board_2_temp_deg_c = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->board_2_temp_deg_c = (int8_t)board_2_temp_deg_c;
    pwr_stg_temp_deg_c = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->pwr_stg_temp_deg_c = (int8_t)pwr_stg_temp_deg_c;
    e_machine_temp_1_deg_c = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->e_machine_temp_1_deg_c = (int8_t)e_machine_temp_1_deg_c;
    e_machine_temp_2_deg_c = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->e_machine_temp_2_deg_c = (int8_t)e_machine_temp_2_deg_c;

    return (0);
}

int inverter_emcu_state_4_right_init(struct inverter_emcu_state_4_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_4_right_t));

    return 0;
}

int8_t inverter_emcu_state_4_right_board_1_temp_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_right_board_1_temp_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_right_board_1_temp_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_right_board_2_temp_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_right_board_2_temp_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_right_board_2_temp_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_right_pwr_stg_temp_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_right_pwr_stg_temp_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_right_pwr_stg_temp_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_right_e_machine_temp_1_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_right_e_machine_temp_1_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_right_e_machine_temp_1_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t inverter_emcu_state_4_right_e_machine_temp_2_deg_c_encode(float value)
{
    return (int8_t)(value - 80.0f);
}

float inverter_emcu_state_4_right_e_machine_temp_2_deg_c_decode(int8_t value)
{
    return ((float)value + 80.0f);
}

bool inverter_emcu_state_4_right_e_machine_temp_2_deg_c_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_5_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_5_right_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->cmd_src_app, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->ctrl_type_app, 3u, 0x38u);
    dst_p[1] |= pack_left_shift_u8(src_p->ctrl_mode_app, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->pos_fb_src_app, 4u, 0xf0u);

    return (2);
}

int inverter_emcu_state_5_right_unpack(
    struct inverter_emcu_state_5_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->cmd_src_app = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->ctrl_type_app = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->ctrl_mode_app = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->pos_fb_src_app = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);

    return (0);
}

int inverter_emcu_state_5_right_init(struct inverter_emcu_state_5_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_5_right_t));

    return 0;
}

uint8_t inverter_emcu_state_5_right_cmd_src_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_right_cmd_src_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_right_cmd_src_app_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t inverter_emcu_state_5_right_ctrl_type_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_right_ctrl_type_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_right_ctrl_type_app_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t inverter_emcu_state_5_right_ctrl_mode_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_right_ctrl_mode_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_right_ctrl_mode_app_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_state_5_right_pos_fb_src_app_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_5_right_pos_fb_src_app_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_5_right_pos_fb_src_app_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int inverter_emcu_state_6_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_6_right_t *src_p,
    size_t size)
{
    uint16_t ac_bus_power_w;
    uint16_t ac_bus_voltage_v;
    uint16_t dc_bus_power_w;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->dc_bus_voltage_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->dc_bus_voltage_v, 8u, 0x03u);
    ac_bus_power_w = (uint16_t)src_p->ac_bus_power_w;
    dst_p[1] |= pack_left_shift_u16(ac_bus_power_w, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(ac_bus_power_w, 6u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(ac_bus_power_w, 14u, 0x03u);
    dc_bus_power_w = (uint16_t)src_p->dc_bus_power_w;
    dst_p[4] |= pack_left_shift_u16(dc_bus_power_w, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(dc_bus_power_w, 8u, 0xffu);
    ac_bus_voltage_v = (uint16_t)src_p->ac_bus_voltage_v;
    dst_p[6] |= pack_left_shift_u16(ac_bus_voltage_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(ac_bus_voltage_v, 8u, 0xffu);

    return (8);
}

int inverter_emcu_state_6_right_unpack(
    struct inverter_emcu_state_6_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t ac_bus_power_w;
    uint16_t ac_bus_voltage_v;
    uint16_t dc_bus_power_w;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->dc_bus_voltage_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->dc_bus_voltage_v |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    ac_bus_power_w = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    ac_bus_power_w |= unpack_left_shift_u16(src_p[2], 6u, 0xffu);
    ac_bus_power_w |= unpack_left_shift_u16(src_p[3], 14u, 0x03u);
    dst_p->ac_bus_power_w = (int16_t)ac_bus_power_w;
    dc_bus_power_w = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dc_bus_power_w |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->dc_bus_power_w = (int16_t)dc_bus_power_w;
    ac_bus_voltage_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    ac_bus_voltage_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->ac_bus_voltage_v = (int16_t)ac_bus_voltage_v;

    return (0);
}

int inverter_emcu_state_6_right_init(struct inverter_emcu_state_6_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_6_right_t));

    return 0;
}

uint16_t inverter_emcu_state_6_right_dc_bus_voltage_v_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_6_right_dc_bus_voltage_v_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_6_right_dc_bus_voltage_v_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int16_t inverter_emcu_state_6_right_ac_bus_power_w_encode(float value)
{
    return (int16_t)(value / 32.767f);
}

float inverter_emcu_state_6_right_ac_bus_power_w_decode(int16_t value)
{
    return ((float)value * 32.767f);
}

bool inverter_emcu_state_6_right_ac_bus_power_w_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_6_right_dc_bus_power_w_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_6_right_dc_bus_power_w_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_6_right_dc_bus_power_w_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_6_right_ac_bus_voltage_v_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_6_right_ac_bus_voltage_v_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_6_right_ac_bus_voltage_v_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_7_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_7_right_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->dem, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->dem, 8u, 0xffu);

    return (2);
}

int inverter_emcu_state_7_right_unpack(
    struct inverter_emcu_state_7_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->dem = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->dem |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int inverter_emcu_state_7_right_init(struct inverter_emcu_state_7_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_7_right_t));

    return 0;
}

uint16_t inverter_emcu_state_7_right_dem_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_state_7_right_dem_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_7_right_dem_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_8_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_8_right_t *src_p,
    size_t size)
{
    uint16_t setpoint_app_d_a;
    uint16_t setpoint_app_q_a;
    uint16_t torque_max_feas_ndm;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    torque_max_feas_ndm = (uint16_t)src_p->torque_max_feas_ndm;
    dst_p[0] |= pack_left_shift_u16(torque_max_feas_ndm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(torque_max_feas_ndm, 8u, 0xffu);
    setpoint_app_d_a = (uint16_t)src_p->setpoint_app_d_a;
    dst_p[2] |= pack_left_shift_u16(setpoint_app_d_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(setpoint_app_d_a, 8u, 0xffu);
    setpoint_app_q_a = (uint16_t)src_p->setpoint_app_q_a;
    dst_p[4] |= pack_left_shift_u16(setpoint_app_q_a, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(setpoint_app_q_a, 8u, 0xffu);

    return (6);
}

int inverter_emcu_state_8_right_unpack(
    struct inverter_emcu_state_8_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t setpoint_app_d_a;
    uint16_t setpoint_app_q_a;
    uint16_t torque_max_feas_ndm;

    if (size < 6u) {
        return (-EINVAL);
    }

    torque_max_feas_ndm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    torque_max_feas_ndm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->torque_max_feas_ndm = (int16_t)torque_max_feas_ndm;
    setpoint_app_d_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    setpoint_app_d_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->setpoint_app_d_a = (int16_t)setpoint_app_d_a;
    setpoint_app_q_a = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    setpoint_app_q_a |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->setpoint_app_q_a = (int16_t)setpoint_app_q_a;

    return (0);
}

int inverter_emcu_state_8_right_init(struct inverter_emcu_state_8_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_8_right_t));

    return 0;
}

int16_t inverter_emcu_state_8_right_torque_max_feas_ndm_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_8_right_torque_max_feas_ndm_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_8_right_torque_max_feas_ndm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_8_right_setpoint_app_d_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_8_right_setpoint_app_d_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_8_right_setpoint_app_d_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_state_8_right_setpoint_app_q_a_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_state_8_right_setpoint_app_q_a_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_state_8_right_setpoint_app_q_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_state_9_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_state_9_right_t *src_p,
    size_t size)
{
    uint16_t torque_est_nm;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->e2_e_p1_crc, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_zero, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_cnt, 4u, 0xf0u);
    torque_est_nm = (uint16_t)src_p->torque_est_nm;
    dst_p[2] |= pack_left_shift_u16(torque_est_nm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(torque_est_nm, 8u, 0xffu);

    return (4);
}

int inverter_emcu_state_9_right_unpack(
    struct inverter_emcu_state_9_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t torque_est_nm;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->e2_e_p1_crc = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->e2_e_p1_zero = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->e2_e_p1_cnt = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    torque_est_nm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    torque_est_nm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_est_nm = (int16_t)torque_est_nm;

    return (0);
}

int inverter_emcu_state_9_right_init(struct inverter_emcu_state_9_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_state_9_right_t));

    return 0;
}

uint8_t inverter_emcu_state_9_right_e2_e_p1_crc_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_9_right_e2_e_p1_crc_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_right_e2_e_p1_crc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_state_9_right_e2_e_p1_zero_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_9_right_e2_e_p1_zero_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_right_e2_e_p1_zero_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_state_9_right_e2_e_p1_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_state_9_right_e2_e_p1_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_right_e2_e_p1_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int16_t inverter_emcu_state_9_right_torque_est_nm_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_state_9_right_torque_est_nm_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_state_9_right_torque_est_nm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_1_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_1_right_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->e2_e_p1_crc, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_zero, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_cnt, 4u, 0xf0u);
    dst_p[2] |= pack_left_shift_u8(src_p->app_state_req, 0u, 0xffu);

    return (3);
}

int inverter_emcu_setpoint_1_right_unpack(
    struct inverter_emcu_setpoint_1_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->e2_e_p1_crc = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->e2_e_p1_zero = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->e2_e_p1_cnt = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    dst_p->app_state_req = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int inverter_emcu_setpoint_1_right_init(struct inverter_emcu_setpoint_1_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_1_right_t));

    return 0;
}

uint8_t inverter_emcu_setpoint_1_right_e2_e_p1_crc_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_right_e2_e_p1_crc_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_right_e2_e_p1_crc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_setpoint_1_right_e2_e_p1_zero_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_right_e2_e_p1_zero_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_right_e2_e_p1_zero_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_setpoint_1_right_e2_e_p1_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_right_e2_e_p1_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_right_e2_e_p1_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_setpoint_1_right_app_state_req_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_1_right_app_state_req_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_1_right_app_state_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_2_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_2_right_t *src_p,
    size_t size)
{
    uint16_t current_d_a_req;
    uint16_t current_q_a_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    current_d_a_req = (uint16_t)src_p->current_d_a_req;
    dst_p[0] |= pack_left_shift_u16(current_d_a_req, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current_d_a_req, 8u, 0xffu);
    current_q_a_req = (uint16_t)src_p->current_q_a_req;
    dst_p[2] |= pack_left_shift_u16(current_q_a_req, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_q_a_req, 8u, 0xffu);

    return (4);
}

int inverter_emcu_setpoint_2_right_unpack(
    struct inverter_emcu_setpoint_2_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_d_a_req;
    uint16_t current_q_a_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    current_d_a_req = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current_d_a_req |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current_d_a_req = (int16_t)current_d_a_req;
    current_q_a_req = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_q_a_req |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_q_a_req = (int16_t)current_q_a_req;

    return (0);
}

int inverter_emcu_setpoint_2_right_init(struct inverter_emcu_setpoint_2_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_2_right_t));

    return 0;
}

int16_t inverter_emcu_setpoint_2_right_current_d_a_req_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_setpoint_2_right_current_d_a_req_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_setpoint_2_right_current_d_a_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_emcu_setpoint_2_right_current_q_a_req_encode(float value)
{
    return (int16_t)(value / 0.03125f);
}

float inverter_emcu_setpoint_2_right_current_q_a_req_decode(int16_t value)
{
    return ((float)value * 0.03125f);
}

bool inverter_emcu_setpoint_2_right_current_q_a_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_3_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_3_right_t *src_p,
    size_t size)
{
    uint16_t torque_nm_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->e2_e_p1_crc, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_zero, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->e2_e_p1_cnt, 4u, 0xf0u);
    torque_nm_req = (uint16_t)src_p->torque_nm_req;
    dst_p[2] |= pack_left_shift_u16(torque_nm_req, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(torque_nm_req, 8u, 0xffu);

    return (4);
}

int inverter_emcu_setpoint_3_right_unpack(
    struct inverter_emcu_setpoint_3_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t torque_nm_req;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->e2_e_p1_crc = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->e2_e_p1_zero = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->e2_e_p1_cnt = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    torque_nm_req = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    torque_nm_req |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_nm_req = (int16_t)torque_nm_req;

    return (0);
}

int inverter_emcu_setpoint_3_right_init(struct inverter_emcu_setpoint_3_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_3_right_t));

    return 0;
}

uint8_t inverter_emcu_setpoint_3_right_e2_e_p1_crc_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_3_right_e2_e_p1_crc_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_right_e2_e_p1_crc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t inverter_emcu_setpoint_3_right_e2_e_p1_zero_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_3_right_e2_e_p1_zero_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_right_e2_e_p1_zero_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t inverter_emcu_setpoint_3_right_e2_e_p1_cnt_encode(float value)
{
    return (uint8_t)(value);
}

float inverter_emcu_setpoint_3_right_e2_e_p1_cnt_decode(uint8_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_right_e2_e_p1_cnt_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int16_t inverter_emcu_setpoint_3_right_torque_nm_req_encode(float value)
{
    return (int16_t)(value);
}

float inverter_emcu_setpoint_3_right_torque_nm_req_decode(int16_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_3_right_torque_nm_req_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_setpoint_4_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_4_right_t *src_p,
    size_t size)
{
    uint32_t speed_erpm;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    speed_erpm = (uint32_t)src_p->speed_erpm;
    dst_p[0] |= pack_left_shift_u32(speed_erpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(speed_erpm, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(speed_erpm, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(speed_erpm, 24u, 0xffu);

    return (4);
}

int inverter_emcu_setpoint_4_right_unpack(
    struct inverter_emcu_setpoint_4_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t speed_erpm;

    if (size < 4u) {
        return (-EINVAL);
    }

    speed_erpm = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    speed_erpm |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    speed_erpm |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    speed_erpm |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->speed_erpm = (int32_t)speed_erpm;

    return (0);
}

int inverter_emcu_setpoint_4_right_init(struct inverter_emcu_setpoint_4_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_4_right_t));

    return 0;
}

int32_t inverter_emcu_setpoint_4_right_speed_erpm_encode(float value)
{
    return (int32_t)(value);
}

float inverter_emcu_setpoint_4_right_speed_erpm_decode(int32_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_4_right_speed_erpm_is_in_range(int32_t value)
{
    return ((value >= -2147480000) && (value <= 2147480000));
}

int inverter_emcu_setpoint_6_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_setpoint_6_right_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->pwm_freq_k_hz, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pwm_freq_k_hz, 8u, 0xffu);

    return (2);
}

int inverter_emcu_setpoint_6_right_unpack(
    struct inverter_emcu_setpoint_6_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->pwm_freq_k_hz = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pwm_freq_k_hz |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int inverter_emcu_setpoint_6_right_init(struct inverter_emcu_setpoint_6_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_setpoint_6_right_t));

    return 0;
}

uint16_t inverter_emcu_setpoint_6_right_pwm_freq_k_hz_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_setpoint_6_right_pwm_freq_k_hz_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_setpoint_6_right_pwm_freq_k_hz_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int inverter_emcu_debug_1_right_pack(
    uint8_t *dst_p,
    const struct inverter_emcu_debug_1_right_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->e_machine_angle_fract16, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->e_machine_angle_fract16, 8u, 0xffu);

    return (2);
}

int inverter_emcu_debug_1_right_unpack(
    struct inverter_emcu_debug_1_right_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->e_machine_angle_fract16 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->e_machine_angle_fract16 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int inverter_emcu_debug_1_right_init(struct inverter_emcu_debug_1_right_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_emcu_debug_1_right_t));

    return 0;
}

uint16_t inverter_emcu_debug_1_right_e_machine_angle_fract16_encode(float value)
{
    return (uint16_t)(value);
}

float inverter_emcu_debug_1_right_e_machine_angle_fract16_decode(uint16_t value)
{
    return ((float)value);
}

bool inverter_emcu_debug_1_right_e_machine_angle_fract16_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
